camera:
  fps: 30
  index: 0
  resolution:
  - 640
  - 480
engines:
  mediapipe:
    max_num_hands: 2
    min_detection_confidence: 0.5
    min_tracking_confidence: 0.5
    static_image_mode: false
    draw_landmarks: true
    draw_connections: true
logging:
  format: '[%(levelname)s] %(asctime)s - %(name)s - %(message)s'
  handlers:
    console: true
    file: log/app.log
  level: INFO
